title: Mahathi Dhulipala Portfolio
description: Professional portfolio of Mahathi Dhulipala - IT Manager & Research Data Analyst
url: "https://github.com/MahathiDhulipala/Portfolio" # or your custom domain
theme: jekyll-theme-minimal